FROM registry.redhat.io/rhel8/podman:latest

LABEL email=catsy@naver.com

# ENV PORT 8080

# RUN yum install -y httpd && yum clean all

# USER apache

# EXPOSE ${PORT}

# CMD ["httpd","-D","FOREGROUND"]
 CMD ["/bin/bash","-c" "while true; do echo date ; done"]