FROM registry.redhat.io/rhel8/rhel:latest

LABEL email=catsy@naver.com

# ENV PORT 8080

# RUN yum install -y httpd && yum clean all

# USER apache

# EXPOSE ${PORT}

CMD ["httpd","-D","FOREGROUND"]
# CMD ["while true; do echo \"TEST\"; done"]